function cols = acorn_training_progress_columns()
% acorn_training_progress_columns -- the progress.csv header, in order.
% Must stay identical to PROGRESS_COLUMNS in agent/training_common.py.
% New columns are only ever appended at the end: acorn_training_append_progress
% extends an older file's header by padding its rows, and
% summarize_training.py reads an older header as a prefix.
cols = {'timestamp', 'trainee', 'area', 'task', 'session', 'stage', 'mode', 'pass', ...
        'subset', 'n_items', 'n_visited', 'n_scored', 'n_contested', ...
        'n_ref_keep_scored', 'n_ref_delete_scored', 'agreement', 'kappa', ...
        'false_keep', 'false_delete', 'motion_ref_n', 'motion_tagged_m', ...
        'motion_deleted_any', 'motion_false_tags', 'n_flagged', 'median_sec', ...
        'total_sec', 'result_file', 'repo_hash', ...
        'contested_with_ref', 'contested_with_model', 'n_corrected'};
end
