"""
review_prep.py - shared helpers for preparing a session for human review.

Two things live here so the watcher, push_review_bundle.py and regen_launchers.py
all agree:

1. The self-locating run_final_review.m launcher. `session_dir` resolves to the
   folder the launcher lives in (via mfilename), so a session can be reviewed
   from ANY machine/drive once the CNMFe repo is on the MATLAB path.
2. The "out for review" assignment marker (review_assigned.txt), written into the
   local session folder when a session is staged out, so REVIEW_QUEUE.md can show
   it as taken and the same file is never handed to two machines.
"""
from datetime import datetime
from pathlib import Path

ASSIGNMENT_MARKER = "review_assigned.txt"


def launcher_text(repo_root) -> str:
    """Self-locating run_final_review.m contents."""
    repo = str(repo_root).replace("\\", "/")
    return (
        "%% run_final_review.m -- auto-generated by CNMFe agent\n"
        "%% Open MATLAB, navigate to this folder, and run this script.\n"
        "%% Portable: session_dir self-locates to this file's folder. The CNMFe\n"
        "%% repo must be on your MATLAB path (run cnmfe_setup.m once, or\n"
        "%% addpath(genpath(<repo_root>))).\n\n"
        "session_dir = fileparts(mfilename('fullpath'));\n"
        "if ~isempty(which('CNMFe_final_save'))\n"
        "    CNMFe_final_save;\n"
        f"elseif isfile('{repo}/CNMFe_final_save.m')\n"
        f"    run('{repo}/CNMFe_final_save.m');\n"
        "else\n"
        "    error('CNMFe_final_save.m not found. Add the CNMFe repo to your MATLAB path (run cnmfe_setup.m or addpath(genpath(<repo_root>))).');\n"
        "end\n"
    )


def write_launcher(dest_dir, repo_root) -> Path:
    """Write a fresh self-locating run_final_review.m into dest_dir."""
    dest = Path(dest_dir) / "run_final_review.m"
    dest.write_text(launcher_text(repo_root))
    return dest


def write_assignment(session_dir, assignee=None) -> Path:
    """Mark a session 'out for review' (a local marker; never sent to the server)."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    text = f"assigned: {ts}\nto: {assignee or '-'}\nby: push_review_bundle.py\n"
    p = Path(session_dir) / ASSIGNMENT_MARKER
    p.write_text(text)
    return p


def read_assignment(session_dir):
    """Return the assignment marker as a dict, or None if the session is not out."""
    p = Path(session_dir) / ASSIGNMENT_MARKER
    if not p.exists():
        return None
    info = {}
    try:
        for line in p.read_text(encoding="utf-8").splitlines():
            if ":" in line:
                k, _, v = line.partition(":")
                info[k.strip()] = v.strip()
    except Exception:
        pass
    return info or {"assigned": "?", "to": "-"}
